# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CMPT276App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CMPT276App
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'SwiftKeychainWrapper'
pod 'Firebase/Storage'
pod 'Charts'
pod 'ChartsRealm'

  target 'CMPT276AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CMPT276AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
